import 'package:asklora_mobile_app/feature/user/account/bloc/disclosure_affiliation/bloc/disclosure_affiliation_bloc.dart';
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';

void main() async {
  group('*Disclosure & AFfiliation Bloc Test*', () {
    late DisclosureAffiliationBloc disclosureAffiliationBloc;

    setUp(() async {
      disclosureAffiliationBloc = DisclosureAffiliationBloc();
    });

    test(
        'init state data should be "null" on all question and "empty string" on optional text input',
        () {
      expect(
          disclosureAffiliationBloc.state,
          const DisclosureAffiliationState(
            isAffiliated: null,
            affiliateCompanyName: '',
            affiliateCompanyAddress: '',
            affiliateCompanyCity: '',
            affiliateCompanyState: '',
            affiliateCompanyCountry: '',
            affiliateCompanyEmail: '',
            isSeniorExecutive: null,
            controlledPersonCompanyName: '',
            controlledPersonCompanyAddress: '',
            controlledPersonCompanyCity: '',
            controlledPersonCompanyState: '',
            controlledPersonCompanyCountry: '',
            controlledPersonCompanyEmail: '',
            isSeniorPolitical: null,
            isFamilyMember: null,
            firstNameOfFamilyMember: '',
            lastNameOfFamilyMember: '',
            isAssociates: null,
            nameOfAffiliatedPerson: '',
            isOwner: null,
            nameOfJointAccount: '',
            isEmployee: null,
          ));
    });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 1 = "Yes"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo1Changed(true)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: true,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 1 = "Yes" and filled affiliate form',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo1Changed(true)),
              bloc.add(const AffiliateCompanyNameChanged('qwe')),
              bloc.add(const AffiliateCompanyAddressChanged('asd')),
              bloc.add(const AffiliateCompanyCityChanged('zxc')),
              bloc.add(const AffiliateCompanyStateChanged('wer')),
              bloc.add(const AffiliateCompanyCountryChanged('sdf')),
              bloc.add(const AffiliateCompanyEmailChanged('qwe@mail.com'))
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: true,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: true,
                affiliateCompanyName: 'qwe',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: true,
                affiliateCompanyName: 'qwe',
                affiliateCompanyAddress: 'asd',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: true,
                affiliateCompanyName: 'qwe',
                affiliateCompanyAddress: 'asd',
                affiliateCompanyCity: 'zxc',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: true,
                affiliateCompanyName: 'qwe',
                affiliateCompanyAddress: 'asd',
                affiliateCompanyCity: 'zxc',
                affiliateCompanyState: 'wer',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: true,
                affiliateCompanyName: 'qwe',
                affiliateCompanyAddress: 'asd',
                affiliateCompanyCity: 'zxc',
                affiliateCompanyState: 'wer',
                affiliateCompanyCountry: 'sdf',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: true,
                affiliateCompanyName: 'qwe',
                affiliateCompanyAddress: 'asd',
                affiliateCompanyCity: 'zxc',
                affiliateCompanyState: 'wer',
                affiliateCompanyCountry: 'sdf',
                affiliateCompanyEmail: 'qwe@mail.com',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 1 = "No"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo1Changed(false)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });

    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 2 = "Yes"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo2Changed(true)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: true,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });

    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 2 = "Yes" and filled controlled person form',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo2Changed(true)),
              bloc.add(const ControlledPersonCompanyNameChanged('qwe')),
              bloc.add(const ControlledPersonCompanyAddressChanged('asd')),
              bloc.add(const ControlledPersonCompanyCityChanged('zxc')),
              bloc.add(const ControlledPersonCompanyStateChanged('wer')),
              bloc.add(const ControlledPersonCompanyCountryChanged('sdf')),
              bloc.add(
                  const ControlledPersonCompanyEmailChanged('qwe@mail.com')),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: true,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: true,
                controlledPersonCompanyName: 'qwe',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: true,
                controlledPersonCompanyName: 'qwe',
                controlledPersonCompanyAddress: 'asd',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: true,
                controlledPersonCompanyName: 'qwe',
                controlledPersonCompanyAddress: 'asd',
                controlledPersonCompanyCity: 'zxc',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: true,
                controlledPersonCompanyName: 'qwe',
                controlledPersonCompanyAddress: 'asd',
                controlledPersonCompanyCity: 'zxc',
                controlledPersonCompanyState: 'wer',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: true,
                controlledPersonCompanyName: 'qwe',
                controlledPersonCompanyAddress: 'asd',
                controlledPersonCompanyCity: 'zxc',
                controlledPersonCompanyState: 'wer',
                controlledPersonCompanyCountry: 'sdf',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: true,
                controlledPersonCompanyName: 'qwe',
                controlledPersonCompanyAddress: 'asd',
                controlledPersonCompanyCity: 'zxc',
                controlledPersonCompanyState: 'wer',
                controlledPersonCompanyCountry: 'sdf',
                controlledPersonCompanyEmail: 'qwe@mail.com',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });

    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 2 = "No"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo2Changed(false)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });

    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 3 = "Yes"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo3Changed(true)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: true,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 3 = "No"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo3Changed(false)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 4 = "Yes"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo4Changed(true)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: true,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 4 = "Yes" and filled form for isFamily = true',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo4Changed(true)),
              bloc.add(const FirstNameOfFamilyMemberChanged('qwe')),
              bloc.add(const LastNameOfFamilyMemberChanged('asd')),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: true,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: true,
                firstNameOfFamilyMember: 'qwe',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: true,
                firstNameOfFamilyMember: 'qwe',
                lastNameOfFamilyMember: 'asd',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });

    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 4 = "No"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo4Changed(false)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });

    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 5 = "Yes"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo5Changed(true)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: true,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 5 = "Yes" and filled name of affiliated person text input',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo5Changed(true)),
              bloc.add(const NameOfAffiliatedChanged('qwe')),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: true,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: true,
                nameOfAffiliatedPerson: 'qwe',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 5 = "No"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo5Changed(false)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: false,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });

    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 6 = "Yes"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo6Changed(true)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: true,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 6 = "No" and filled name of joint account input text ',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo6Changed(false)),
              bloc.add(const NameOfJointAccountChanged('qwe')),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: false,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: false,
                nameOfJointAccount: 'qwe',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 6 = "No"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo6Changed(false)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: false,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 7 = "Yes"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo7Changed(true)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: true,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Question no 7 = "No"',
        build: () => disclosureAffiliationBloc,
        act: (bloc) => {
              bloc.add(const QuestionNo7Changed(false)),
            },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: null,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: false,
              ),
            });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'Select option "No" for all question',
        build: () => disclosureAffiliationBloc,
        act: (bloc) {
          bloc.add(const QuestionNo1Changed(false));
          bloc.add(const QuestionNo2Changed(false));
          bloc.add(const QuestionNo3Changed(false));
          bloc.add(const QuestionNo4Changed(false));
          bloc.add(const QuestionNo5Changed(false));
          bloc.add(const QuestionNo6Changed(false));
          bloc.add(const QuestionNo7Changed(false));
        },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: false,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: false,
                nameOfAffiliatedPerson: '',
                isOwner: false,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: false,
                nameOfAffiliatedPerson: '',
                isOwner: false,
                nameOfJointAccount: '',
                isEmployee: false,
              ),
            });

    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
      'Select option "Yes" for all question',
      build: () => disclosureAffiliationBloc,
      act: (bloc) => {
        bloc.add(const QuestionNo1Changed(true)),
        bloc.add(const QuestionNo2Changed(true)),
        bloc.add(const QuestionNo3Changed(true)),
        bloc.add(const QuestionNo4Changed(true)),
        bloc.add(const QuestionNo5Changed(true)),
        bloc.add(const QuestionNo6Changed(true)),
        bloc.add(const QuestionNo7Changed(true)),
      },
      expect: () => {
        const DisclosureAffiliationState(
          isAffiliated: true,
          affiliateCompanyName: '',
          affiliateCompanyAddress: '',
          affiliateCompanyCity: '',
          affiliateCompanyState: '',
          affiliateCompanyCountry: '',
          affiliateCompanyEmail: '',
          isSeniorExecutive: null,
          controlledPersonCompanyName: '',
          controlledPersonCompanyAddress: '',
          controlledPersonCompanyCity: '',
          controlledPersonCompanyState: '',
          controlledPersonCompanyCountry: '',
          controlledPersonCompanyEmail: '',
          isSeniorPolitical: null,
          isFamilyMember: null,
          firstNameOfFamilyMember: '',
          lastNameOfFamilyMember: '',
          isAssociates: null,
          nameOfAffiliatedPerson: '',
          isOwner: null,
          nameOfJointAccount: '',
          isEmployee: null,
        ),
        const DisclosureAffiliationState(
          isAffiliated: true,
          affiliateCompanyName: '',
          affiliateCompanyAddress: '',
          affiliateCompanyCity: '',
          affiliateCompanyState: '',
          affiliateCompanyCountry: '',
          affiliateCompanyEmail: '',
          isSeniorExecutive: true,
          controlledPersonCompanyName: '',
          controlledPersonCompanyAddress: '',
          controlledPersonCompanyCity: '',
          controlledPersonCompanyState: '',
          controlledPersonCompanyCountry: '',
          controlledPersonCompanyEmail: '',
          isSeniorPolitical: null,
          isFamilyMember: null,
          firstNameOfFamilyMember: '',
          lastNameOfFamilyMember: '',
          isAssociates: null,
          nameOfAffiliatedPerson: '',
          isOwner: null,
          nameOfJointAccount: '',
          isEmployee: null,
        ),
        const DisclosureAffiliationState(
          isAffiliated: true,
          affiliateCompanyName: '',
          affiliateCompanyAddress: '',
          affiliateCompanyCity: '',
          affiliateCompanyState: '',
          affiliateCompanyCountry: '',
          affiliateCompanyEmail: '',
          isSeniorExecutive: true,
          controlledPersonCompanyName: '',
          controlledPersonCompanyAddress: '',
          controlledPersonCompanyCity: '',
          controlledPersonCompanyState: '',
          controlledPersonCompanyCountry: '',
          controlledPersonCompanyEmail: '',
          isSeniorPolitical: true,
          isFamilyMember: null,
          firstNameOfFamilyMember: '',
          lastNameOfFamilyMember: '',
          isAssociates: null,
          nameOfAffiliatedPerson: '',
          isOwner: null,
          nameOfJointAccount: '',
          isEmployee: null,
        ),
        const DisclosureAffiliationState(
          isAffiliated: true,
          affiliateCompanyName: '',
          affiliateCompanyAddress: '',
          affiliateCompanyCity: '',
          affiliateCompanyState: '',
          affiliateCompanyCountry: '',
          affiliateCompanyEmail: '',
          isSeniorExecutive: true,
          controlledPersonCompanyName: '',
          controlledPersonCompanyAddress: '',
          controlledPersonCompanyCity: '',
          controlledPersonCompanyState: '',
          controlledPersonCompanyCountry: '',
          controlledPersonCompanyEmail: '',
          isSeniorPolitical: true,
          isFamilyMember: true,
          firstNameOfFamilyMember: '',
          lastNameOfFamilyMember: '',
          isAssociates: null,
          nameOfAffiliatedPerson: '',
          isOwner: null,
          nameOfJointAccount: '',
          isEmployee: null,
        ),
        const DisclosureAffiliationState(
          isAffiliated: true,
          affiliateCompanyName: '',
          affiliateCompanyAddress: '',
          affiliateCompanyCity: '',
          affiliateCompanyState: '',
          affiliateCompanyCountry: '',
          affiliateCompanyEmail: '',
          isSeniorExecutive: true,
          controlledPersonCompanyName: '',
          controlledPersonCompanyAddress: '',
          controlledPersonCompanyCity: '',
          controlledPersonCompanyState: '',
          controlledPersonCompanyCountry: '',
          controlledPersonCompanyEmail: '',
          isSeniorPolitical: true,
          isFamilyMember: true,
          firstNameOfFamilyMember: '',
          lastNameOfFamilyMember: '',
          isAssociates: true,
          nameOfAffiliatedPerson: '',
          isOwner: null,
          nameOfJointAccount: '',
          isEmployee: null,
        ),
        const DisclosureAffiliationState(
          isAffiliated: true,
          affiliateCompanyName: '',
          affiliateCompanyAddress: '',
          affiliateCompanyCity: '',
          affiliateCompanyState: '',
          affiliateCompanyCountry: '',
          affiliateCompanyEmail: '',
          isSeniorExecutive: true,
          controlledPersonCompanyName: '',
          controlledPersonCompanyAddress: '',
          controlledPersonCompanyCity: '',
          controlledPersonCompanyState: '',
          controlledPersonCompanyCountry: '',
          controlledPersonCompanyEmail: '',
          isSeniorPolitical: true,
          isFamilyMember: true,
          firstNameOfFamilyMember: '',
          lastNameOfFamilyMember: '',
          isAssociates: true,
          nameOfAffiliatedPerson: '',
          isOwner: true,
          nameOfJointAccount: '',
          isEmployee: null,
        ),
        const DisclosureAffiliationState(
          isAffiliated: true,
          affiliateCompanyName: '',
          affiliateCompanyAddress: '',
          affiliateCompanyCity: '',
          affiliateCompanyState: '',
          affiliateCompanyCountry: '',
          affiliateCompanyEmail: '',
          isSeniorExecutive: true,
          controlledPersonCompanyName: '',
          controlledPersonCompanyAddress: '',
          controlledPersonCompanyCity: '',
          controlledPersonCompanyState: '',
          controlledPersonCompanyCountry: '',
          controlledPersonCompanyEmail: '',
          isSeniorPolitical: true,
          isFamilyMember: true,
          firstNameOfFamilyMember: '',
          lastNameOfFamilyMember: '',
          isAssociates: true,
          nameOfAffiliatedPerson: '',
          isOwner: true,
          nameOfJointAccount: '',
          isEmployee: true,
        ),
      },
    );

    tearDown(() => {disclosureAffiliationBloc.close()});
  });
}
