import 'package:asklora_mobile_app/feature/user/account/bloc/disclosure_affiliation/bloc/disclosure_affiliation_bloc.dart';
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';

void main() async {
  group('*Disclosure & AFfiliation Bloc Test*', () {
    late DisclosureAffiliationBloc disclosureAffiliationBloc;

    setUp(() async {
      disclosureAffiliationBloc = DisclosureAffiliationBloc();
    });

    test(
        'init state data should be "null" on all question and "empty string" on optional text input',
        () {
      expect(
          disclosureAffiliationBloc.state,
          const DisclosureAffiliationState(
            isAffiliated: null,
            affiliateCompanyName: '',
            affiliateCompanyAddress: '',
            affiliateCompanyCity: '',
            affiliateCompanyState: '',
            affiliateCompanyCountry: '',
            affiliateCompanyEmail: '',
            isSeniorExecutive: null,
            controlledPersonCompanyName: '',
            controlledPersonCompanyAddress: '',
            controlledPersonCompanyCity: '',
            controlledPersonCompanyState: '',
            controlledPersonCompanyCountry: '',
            controlledPersonCompanyEmail: '',
            isSeniorPolitical: null,
            isFamilyMember: null,
            firstNameOfFamilyMember: '',
            lastNameOfFamilyMember: '',
            isAssociates: null,
            nameOfAffiliatedPerson: '',
            isOwner: null,
            nameOfJointAccount: '',
            isEmployee: null,
          ));
    });
    blocTest<DisclosureAffiliationBloc, DisclosureAffiliationState>(
        'select option "No" for all question',
        build: () => disclosureAffiliationBloc,
        act: (bloc) {
          bloc.add(const QuestionNo1Changed(false));
          bloc.add(const QuestionNo2Changed(false));
          bloc.add(const QuestionNo3Changed(false));
          bloc.add(const QuestionNo4Changed(false));
          bloc.add(const QuestionNo5Changed(false));
          bloc.add(const QuestionNo6Changed(false));
          bloc.add(const QuestionNo7Changed(false));
        },
        expect: () => {
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: null,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: null,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: null,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: null,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: false,
                nameOfAffiliatedPerson: '',
                isOwner: null,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: false,
                nameOfAffiliatedPerson: '',
                isOwner: false,
                nameOfJointAccount: '',
                isEmployee: null,
              ),
              const DisclosureAffiliationState(
                isAffiliated: false,
                affiliateCompanyName: '',
                affiliateCompanyAddress: '',
                affiliateCompanyCity: '',
                affiliateCompanyState: '',
                affiliateCompanyCountry: '',
                affiliateCompanyEmail: '',
                isSeniorExecutive: false,
                controlledPersonCompanyName: '',
                controlledPersonCompanyAddress: '',
                controlledPersonCompanyCity: '',
                controlledPersonCompanyState: '',
                controlledPersonCompanyCountry: '',
                controlledPersonCompanyEmail: '',
                isSeniorPolitical: false,
                isFamilyMember: false,
                firstNameOfFamilyMember: '',
                lastNameOfFamilyMember: '',
                isAssociates: false,
                nameOfAffiliatedPerson: '',
                isOwner: false,
                nameOfJointAccount: '',
                isEmployee: false,
              ),
            });

    tearDown(() => {disclosureAffiliationBloc.close()});
  });
}
