// Mocks generated by Mockito 5.2.0 from annotations
// in asklora_mobile_app/test/reset_password/reset_password_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:asklora_mobile_app/feature/auth/reset_password/domain/reset_password_api_client.dart'
    as _i6;
import 'package:asklora_mobile_app/feature/auth/reset_password/domain/reset_password_request.dart'
    as _i7;
import 'package:asklora_mobile_app/feature/auth/reset_password/domain/reset_password_response.dart'
    as _i2;
import 'package:asklora_mobile_app/feature/auth/reset_password/repository/reset_password_repository.dart'
    as _i4;
import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResetPasswordResponse_0 extends _i1.Fake
    implements _i2.ResetPasswordResponse {}

class _FakeResponse_1<T> extends _i1.Fake implements _i3.Response<T> {}

/// A class which mocks [ResetPasswordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordRepository extends _i1.Mock
    implements _i4.ResetPasswordRepository {
  MockResetPasswordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ResetPasswordResponse> resetPassword({String? email}) => (super
          .noSuchMethod(Invocation.method(#resetPassword, [], {#email: email}),
              returnValue: Future<_i2.ResetPasswordResponse>.value(
                  _FakeResetPasswordResponse_0()))
      as _i5.Future<_i2.ResetPasswordResponse>);
}

/// A class which mocks [ResetPasswordApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordApiClient extends _i1.Mock
    implements _i6.ResetPasswordApiClient {
  MockResetPasswordApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Response<dynamic>> resetPassword(
          _i7.ResetPasswordRequest? request) =>
      (super.noSuchMethod(Invocation.method(#resetPassword, [request]),
              returnValue: Future<_i3.Response<dynamic>>.value(
                  _FakeResponse_1<dynamic>()))
          as _i5.Future<_i3.Response<dynamic>>);
}
