// Mocks generated by Mockito 5.2.0 from annotations
// in asklora_mobile_app/test/app/app_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:asklora_mobile_app/core/domain/token/token_api_client.dart'
    as _i5;
import 'package:asklora_mobile_app/core/domain/token/token_refresh_request.dart'
    as _i7;
import 'package:asklora_mobile_app/core/domain/token/token_verify_request.dart'
    as _i6;
import 'package:asklora_mobile_app/core/utils/token_validator.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0<T> extends _i1.Fake implements _i2.Response<T> {}

/// A class which mocks [TokenValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenValidator extends _i1.Mock implements _i3.TokenValidator {
  MockTokenValidator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isTokenValid() =>
      (super.noSuchMethod(Invocation.method(#isTokenValid, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<bool> refreshToken() =>
      (super.noSuchMethod(Invocation.method(#refreshToken, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [TokenApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenApiClient extends _i1.Mock implements _i5.TokenApiClient {
  MockTokenApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> verify(_i6.TokenVerifyRequest? request) =>
      (super.noSuchMethod(Invocation.method(#verify, [request]),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_0<dynamic>()))
          as _i4.Future<_i2.Response<dynamic>>);
  @override
  _i4.Future<_i2.Response<dynamic>> refresh(_i7.TokenRefreshRequest? request) =>
      (super.noSuchMethod(Invocation.method(#refresh, [request]),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_0<dynamic>()))
          as _i4.Future<_i2.Response<dynamic>>);
}
