image: cirrusci/flutter:stable

stages:
 - build
 - format
 - analyze
 - test
 - test_echo

test_echo:

  tags:
    - dev

  stage: test_echo

  script:
    - echo "Ci/CD has been disabled for while"

  only:
    - pushes

before_script:

  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
 - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
 - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
 - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ##
  ## Create the SSH directory and give it the right permissions
  ##
 - mkdir -p ~/.ssh
 - chmod 700 ~/.ssh
 - git config --global user.email "darth@empire.com"
 - git config --global user.name "Darth Vader"

  # try to connect to GitLab.com
 - ssh git@gitlab.intra.asklora.store

  # try to clone yourself. A *PUBLIC* key paired to the SSH_PRIVATE_KEY was added as deploy key to this repository
 - git clone git@gitlab.intra.asklora.store:frontend/asklora-mobile-app.git
 - git clone git@gitlab.intra.asklora.store:frontend/asklora-flutter-chart.git


 - flutter clean
 - flutter pub get

build:
 stage: build

 script:
   - flutter build aot

 tags:
   - shared

 only:
   - merge_requests

format:

 tags:
   - dev

 stage: format

 script:
   - make format

 only:
   - pushes

analyze:

 tags:
   - dev

 stage: analyze

 script:
   - make lint

 only:
   - pushes

unit_test:

 tags:
   - dev

 stage: test

 script:
   - make run_test

 only:
   - pushes
