image: cirrusci/flutter:stable

stages:
#  - build
  - format
  - analyze
  - test

before_script:
  - flutter pub get
  - flutter clean

#build:
#  stage: build
#
#  script:
#    - flutter build aot
#
#  tags:
#    - shared
#
#  only:
#    - merge_requests

format:
  stage: format

  script:
    - make format

  only:
    - pushes

analyze:
  stage: analyze

  script:
    - make lint

  only:
    - pushes

unit_test:
  stage: test

  script:
    - make run_test

  only:
    - pushes