image: cirrusci/flutter:stable

stages:
 - build
 - format
 - analyze
 - test
 - test_echo

test_echo:

  tags:
    - dev

  stage: test_echo

  script:
    - echo "Ci/CD has been disabled for while"

  only:
    - pushes

before_script:
 - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.intra.asklora.store/"
#  - mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts
#  - ssh-keyscan -H gitlab.intra.asklora.store >> ~/.ssh/known_hosts
 - flutter clean
 - flutter pub get

build:
 stage: build

 script:
   - flutter build aot

 tags:
   - shared

 only:
   - merge_requests

format:

 tags:
   - dev

 stage: format

 script:
   - make format

 only:
   - pushes

analyze:

 tags:
   - dev

 stage: analyze

 script:
   - make lint

 only:
   - pushes

unit_test:

 tags:
   - dev

 stage: test

 script:
   - make run_test

 only:
   - pushes
