name: asklora_mobile_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  built_value: ^8.3.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_native_splash: ^2.2.3+1
  flutter_secure_storage: ^6.0.0
  json_annotation: ^4.5.0
  logger: any
  shared_preferences: ^2.0.15
  pin_code_fields: ^7.4.0
  url_launcher: ^6.1.4
  signature: ^5.0.1
  dart_ipify: ^1.1.1

  flutter_onfido:
    git:
      url: https://github.com/krishna-gupta-al/flutter_onfido.git
      ref: master

  country_picker:
    git:
      url: https://github.com/asklora/flutter_country_picker.git
      ref: master
  intl: ^0.17.0
  device_info_plus: ^8.0.0
  file_picker: ^5.0.0
  collection: ^1.16.0
  package_info_plus: ^3.0.1
  firebase_core: ^2.1.1
  firebase_crashlytics: ^3.0.3
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.4
  photo_view: ^0.14.0
  carousel_slider: ^4.1.1
  dotted_border: ^2.0.0+3

#dependency_overrides:
#  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  build_runner: ^2.1.11
  built_value_generator: ^8.3.2
  mockito: ^5.2.0
  bloc_test: ^9.0.3
  http_mock_adapter: ^0.3.3
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
