import 'package:flutter/material.dart';

import '../../../core/domain/pair.dart';
import '../../../core/styles/asklora_colors.dart';
import '../../onboarding/ppi/domain/ppi_user_response.dart';
import '../domain/bot_recommendation_model.dart';

List<Pair<String, String>> botRecommendationFaqs = [
  Pair('How can I get a specific stock?',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquet eget egestas egestas sed nisl, at gravida. Amet gravida massa eu fusce arcu urna.'),
  Pair('How can I see more Botstock?',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquet eget egestas egestas sed nisl, at gravida. Amet gravida massa eu fusce arcu urna.'),
  Pair('Why I should invest in Botstock?',
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquet eget egestas egestas sed nisl, at gravida. Amet gravida massa eu fusce arcu urna.'),
];

List<BotRecommendationModel> defaultBotRecommendation = [
  const BotRecommendationModel(1, '', '', '', '', '', 'Pullup', '', 'TESLA', '', '440'),
  const BotRecommendationModel(2, '', '', '', '', '', 'Plank', '', 'TESLA', '', '390'),
  const BotRecommendationModel(3, '', '', '', '', '', 'Squat', '', 'TESLA', '', '100'),
  const BotRecommendationModel(4, '', '', '', '', '', 'Plank', '', 'TESLA', '', '150'),
  const BotRecommendationModel(5, '', '', '', '', '', 'Squat', '', 'TESLA', '', '160'),
  const BotRecommendationModel(6, '', '', '', '', '', 'Pullup', '', 'TESLA', '', '90'),
  const BotRecommendationModel(7, '', '', '', '', '', 'Pullup', '', 'TESLA', '', '20'),
  const BotRecommendationModel(8, '', '', '', '', '', 'Plank', '', 'TESLA', '', '600'),
];

List<RecommendedBot> defaultRecommendedBots = [
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Pullup',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 5))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 2))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 10))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Squat',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 30))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 25))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Pullup',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 60))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Squat',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 70))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 80))),
];

List<RecommendedBot> defaultFreeRecommendedBots = [
  RecommendedBot(
    '1',
    'TSLA',
    'Tesla TSLA',
    '4',
    'Pullup',
    'For stocks that holds a stable position. ',
    'Tesla Inc',
    '303.75',
    '9',
    '10',
    DateTime.now().add(const Duration(days: 5)),
    freeBot: true,
  ),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 2)),
      freeBot: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 10)),
      freeBot: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Squat',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 30)),
      freeBot: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 25)),
      freeBot: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Pullup',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 60)),
      freeBot: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Squat',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 70)),
      freeBot: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 80)),
      freeBot: true),
];

List<RecommendedBot> demonstrationBots = [
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Pullup',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 5)),
      selectable: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 2))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 10)),
      freeBot: true,
      selectable: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Squat',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 30)),
      selectable: true),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 25))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Pullup',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 60))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Squat',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 70))),
  RecommendedBot(
      '1',
      'TSLA',
      'Tesla TSLA',
      '4',
      'Plank',
      'For stocks that holds a stable position. ',
      'Tesla Inc',
      '303.75',
      '9',
      '10',
      DateTime.now().add(const Duration(days: 80))),
];

enum BotType {
  pullUp('Pullup', 'PULLUP', 'Pullup', 'icon_bot_badge_pop_up_message_Pullup',
      AskLoraColors.lime, AskLoraColors.darkerLime),
  squat('Squat', 'SQUAT', 'Squat', 'icon_bot_badge_pop_up_message_squat',
      AskLoraColors.purple, AskLoraColors.darkerPurple,
      expiredTextColor: AskLoraColors.white),
  plank('Plank', 'PLANK', 'Plank', 'icon_bot_badge_pop_up_message_plank',
      AskLoraColors.primaryGreen, AskLoraColors.darkerGreen);

  final String value;
  final String upperCaseName;
  final String name;
  final String botAssetName;
  final Color primaryBgColor;
  final Color secondaryBgColor;
  final Color expiredTextColor;

  const BotType(this.value, this.upperCaseName, this.name, this.botAssetName,
      this.primaryBgColor, this.secondaryBgColor,
      {this.expiredTextColor = AskLoraColors.charcoal});

  static BotType findByString(String botAppType) =>
      BotType.values.firstWhere((element) => element.value == botAppType);
}

enum BotStockFilter {
  all('All'),
  active('Active'),
  pending('Pending');

  final String name;

  const BotStockFilter(this.name);
}
