// Mocks generated by Mockito 5.3.2 from annotations
// in asklora_mobile_app/test/portfolio/portfolio_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:asklora_mobile_app/core/domain/base_response.dart' as _i2;
import 'package:asklora_mobile_app/feature/bot_stock/domain/bot_detail_model.dart'
    as _i7;
import 'package:asklora_mobile_app/feature/bot_stock/domain/bot_recommendation_model.dart'
    as _i10;
import 'package:asklora_mobile_app/feature/bot_stock/domain/orders/bot_active_order_detail_model.dart'
    as _i13;
import 'package:asklora_mobile_app/feature/bot_stock/domain/orders/bot_active_order_model.dart'
    as _i11;
import 'package:asklora_mobile_app/feature/bot_stock/domain/orders/bot_create_order_response.dart'
    as _i14;
import 'package:asklora_mobile_app/feature/bot_stock/presentation/portfolio/domain/portfolio_response.dart'
    as _i5;
import 'package:asklora_mobile_app/feature/bot_stock/presentation/portfolio/repository/portfolio_repository.dart'
    as _i3;
import 'package:asklora_mobile_app/feature/bot_stock/repository/bot_stock_repository.dart'
    as _i6;
import 'package:asklora_mobile_app/feature/bot_stock/utils/bot_stock_utils.dart'
    as _i12;
import 'package:asklora_mobile_app/feature/chart/domain/chart_models.dart'
    as _i8;
import 'package:asklora_mobile_app/feature/chart/domain/chart_studio_animation_model.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PortfolioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioRepository extends _i1.Mock
    implements _i3.PortfolioRepository {
  MockPortfolioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResponse<_i5.PortfolioResponse>> fetchPortfolio() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPortfolio,
          [],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<_i5.PortfolioResponse>>.value(
            _FakeBaseResponse_0<_i5.PortfolioResponse>(
          this,
          Invocation.method(
            #fetchPortfolio,
            [],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i5.PortfolioResponse>>);
}

/// A class which mocks [BotStockRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBotStockRepository extends _i1.Mock
    implements _i6.BotStockRepository {
  MockBotStockRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResponse<_i7.BotDetailModel>> fetchBotDetail(
    String? ticker,
    String? botId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBotDetail,
          [
            ticker,
            botId,
          ],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<_i7.BotDetailModel>>.value(
            _FakeBaseResponse_0<_i7.BotDetailModel>(
          this,
          Invocation.method(
            #fetchBotDetail,
            [
              ticker,
              botId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i7.BotDetailModel>>);
  @override
  _i4.Future<_i2.BaseResponse<List<_i8.ChartDataSet>>> fetchChartDataJson() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChartDataJson,
          [],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i8.ChartDataSet>>>.value(
            _FakeBaseResponse_0<List<_i8.ChartDataSet>>(
          this,
          Invocation.method(
            #fetchChartDataJson,
            [],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i8.ChartDataSet>>>);
  @override
  _i4.Future<_i2.BaseResponse<_i9.ChartStudioAnimationModel>>
      fetchTradeChartDataJson() => (super.noSuchMethod(
            Invocation.method(
              #fetchTradeChartDataJson,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.BaseResponse<_i9.ChartStudioAnimationModel>>.value(
                _FakeBaseResponse_0<_i9.ChartStudioAnimationModel>(
              this,
              Invocation.method(
                #fetchTradeChartDataJson,
                [],
              ),
            )),
          ) as _i4.Future<_i2.BaseResponse<_i9.ChartStudioAnimationModel>>);
  @override
  _i4.Future<_i2.BaseResponse<List<_i10.BotRecommendationModel>>>
      fetchBotRecommendation() => (super.noSuchMethod(
            Invocation.method(
              #fetchBotRecommendation,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.BaseResponse<List<_i10.BotRecommendationModel>>>.value(
                _FakeBaseResponse_0<List<_i10.BotRecommendationModel>>(
              this,
              Invocation.method(
                #fetchBotRecommendation,
                [],
              ),
            )),
          ) as _i4.Future<_i2.BaseResponse<List<_i10.BotRecommendationModel>>>);
  @override
  _i4.Future<_i2.BaseResponse<List<_i10.BotRecommendationModel>>>
      fetchFreeBotRecommendation({bool? isFreeBot = false}) =>
          (super.noSuchMethod(
            Invocation.method(
              #fetchFreeBotRecommendation,
              [],
              {#isFreeBot: isFreeBot},
            ),
            returnValue: _i4.Future<
                    _i2.BaseResponse<List<_i10.BotRecommendationModel>>>.value(
                _FakeBaseResponse_0<List<_i10.BotRecommendationModel>>(
              this,
              Invocation.method(
                #fetchFreeBotRecommendation,
                [],
                {#isFreeBot: isFreeBot},
              ),
            )),
          ) as _i4.Future<_i2.BaseResponse<List<_i10.BotRecommendationModel>>>);
  @override
  _i4.Future<_i2.BaseResponse<List<_i10.BotRecommendationModel>>>
      fetchBotDemonstration() => (super.noSuchMethod(
            Invocation.method(
              #fetchBotDemonstration,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.BaseResponse<List<_i10.BotRecommendationModel>>>.value(
                _FakeBaseResponse_0<List<_i10.BotRecommendationModel>>(
              this,
              Invocation.method(
                #fetchBotDemonstration,
                [],
              ),
            )),
          ) as _i4.Future<_i2.BaseResponse<List<_i10.BotRecommendationModel>>>);
  @override
  _i4.Future<bool> removeInvestmentStyleState() => (super.noSuchMethod(
        Invocation.method(
          #removeInvestmentStyleState,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<_i2.BaseResponse<List<_i11.BotActiveOrderModel>>> activeOrders(
          {_i12.BotStockFilter? botStockFilter}) =>
      (super.noSuchMethod(
        Invocation.method(
          #activeOrders,
          [],
          {#botStockFilter: botStockFilter},
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<List<_i11.BotActiveOrderModel>>>.value(
                _FakeBaseResponse_0<List<_i11.BotActiveOrderModel>>(
          this,
          Invocation.method(
            #activeOrders,
            [],
            {#botStockFilter: botStockFilter},
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i11.BotActiveOrderModel>>>);
  @override
  _i4.Future<
      _i2.BaseResponse<_i13.BotActiveOrderDetailModel>> activeOrderDetail(
          String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #activeOrderDetail,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i13.BotActiveOrderDetailModel>>.value(
                _FakeBaseResponse_0<_i13.BotActiveOrderDetailModel>(
          this,
          Invocation.method(
            #activeOrderDetail,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i13.BotActiveOrderDetailModel>>);
  @override
  _i4.Future<_i2.BaseResponse<_i14.BotCreateOrderResponse>> createOrder({
    required _i10.BotRecommendationModel? botRecommendationModel,
    required double? tradeBotStockAmount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #botRecommendationModel: botRecommendationModel,
            #tradeBotStockAmount: tradeBotStockAmount,
          },
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<_i14.BotCreateOrderResponse>>.value(
                _FakeBaseResponse_0<_i14.BotCreateOrderResponse>(
          this,
          Invocation.method(
            #createOrder,
            [],
            {
              #botRecommendationModel: botRecommendationModel,
              #tradeBotStockAmount: tradeBotStockAmount,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<_i14.BotCreateOrderResponse>>);
  @override
  _i4.Future<_i2.BaseResponse<bool>> cancelOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<bool>>.value(_FakeBaseResponse_0<bool>(
          this,
          Invocation.method(
            #cancelOrder,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<bool>>);
  @override
  _i4.Future<_i2.BaseResponse<bool>> rolloverOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #rolloverOrder,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<bool>>.value(_FakeBaseResponse_0<bool>(
          this,
          Invocation.method(
            #rolloverOrder,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<bool>>);
  @override
  _i4.Future<_i2.BaseResponse<bool>> terminateOrder(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #terminateOrder,
          [orderId],
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<bool>>.value(_FakeBaseResponse_0<bool>(
          this,
          Invocation.method(
            #terminateOrder,
            [orderId],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<bool>>);
}
