// Mocks generated by Mockito 5.3.2 from annotations
// in asklora_mobile_app/test/portfolio/portfolio_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:asklora_mobile_app/core/domain/base_response.dart' as _i2;
import 'package:asklora_mobile_app/feature/bot_stock/domain/bot_recommendation_model.dart'
    as _i6;
import 'package:asklora_mobile_app/feature/bot_stock/presentation/portfolio/domain/portfolio_detail_response.dart'
    as _i8;
import 'package:asklora_mobile_app/feature/bot_stock/presentation/portfolio/repository/portfolio_repository.dart'
    as _i3;
import 'package:asklora_mobile_app/feature/bot_stock/utils/bot_stock_utils.dart'
    as _i7;
import 'package:asklora_mobile_app/feature/chart/domain/chart_models.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PortfolioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioRepository extends _i1.Mock
    implements _i3.PortfolioRepository {
  MockPortfolioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResponse<List<_i5.ChartDataSet>>> fetchChartDataJson() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchChartDataJson,
          [],
        ),
        returnValue: _i4.Future<_i2.BaseResponse<List<_i5.ChartDataSet>>>.value(
            _FakeBaseResponse_0<List<_i5.ChartDataSet>>(
          this,
          Invocation.method(
            #fetchChartDataJson,
            [],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i5.ChartDataSet>>>);
  @override
  _i4.Future<_i2.BaseResponse<List<_i6.BotRecommendationModel>>>
      fetchBotPortfolio(_i7.BotStockFilter? botStockFilter) =>
          (super.noSuchMethod(
            Invocation.method(
              #fetchBotPortfolio,
              [botStockFilter],
            ),
            returnValue: _i4.Future<
                    _i2.BaseResponse<List<_i6.BotRecommendationModel>>>.value(
                _FakeBaseResponse_0<List<_i6.BotRecommendationModel>>(
              this,
              Invocation.method(
                #fetchBotPortfolio,
                [botStockFilter],
              ),
            )),
          ) as _i4.Future<_i2.BaseResponse<List<_i6.BotRecommendationModel>>>);
  @override
  _i4.Future<_i2.BaseResponse<_i8.PortfolioDetailResponse>>
      fetchPortfolioDetail() => (super.noSuchMethod(
            Invocation.method(
              #fetchPortfolioDetail,
              [],
            ),
            returnValue:
                _i4.Future<_i2.BaseResponse<_i8.PortfolioDetailResponse>>.value(
                    _FakeBaseResponse_0<_i8.PortfolioDetailResponse>(
              this,
              Invocation.method(
                #fetchPortfolioDetail,
                [],
              ),
            )),
          ) as _i4.Future<_i2.BaseResponse<_i8.PortfolioDetailResponse>>);
}
