// Mocks generated by Mockito 5.2.0 from annotations
// in asklora_mobile_app/test/deposit/select_bank_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:asklora_mobile_app/feature/deposit/model/bank_details.dart'
    as _i4;
import 'package:asklora_mobile_app/feature/deposit/repository/bank_details_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [BankDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBankDetailsRepository extends _i1.Mock
    implements _i2.BankDetailsRepository {
  MockBankDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BankDetails>> getListBank() => (super.noSuchMethod(
          Invocation.method(#getListBank, []),
          returnValue: Future<List<_i4.BankDetails>>.value(<_i4.BankDetails>[]))
      as _i3.Future<List<_i4.BankDetails>>);
}
