// Mocks generated by Mockito 5.2.0 from annotations
// in asklora_mobile_app/test/deposit/select_bank_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:asklora_mobile_app/feature/deposit/model/list_bank.dart' as _i4;
import 'package:asklora_mobile_app/feature/deposit/repository/list_bank_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ListBankRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockListBankRepository extends _i1.Mock
    implements _i2.ListBankRepository {
  MockListBankRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ListBanks>> getListBank() =>
      (super.noSuchMethod(Invocation.method(#getListBank, []),
              returnValue: Future<List<_i4.ListBanks>>.value(<_i4.ListBanks>[]))
          as _i3.Future<List<_i4.ListBanks>>);
}
