// Mocks generated by Mockito 5.3.2 from annotations
// in asklora_mobile_app/test/sign_up/sign_up_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:asklora_mobile_app/core/domain/base_response.dart' as _i2;
import 'package:asklora_mobile_app/core/domain/otp/get_otp_request.dart' as _i9;
import 'package:asklora_mobile_app/core/utils/storage/shared_preference.dart'
    as _i14;
import 'package:asklora_mobile_app/feature/auth/sign_up/domain/response.dart'
    as _i8;
import 'package:asklora_mobile_app/feature/auth/sign_up/domain/sign_up_api_client.dart'
    as _i10;
import 'package:asklora_mobile_app/feature/auth/sign_up/domain/sign_up_request.dart'
    as _i11;
import 'package:asklora_mobile_app/feature/auth/sign_up/repository/sign_up_repository.dart'
    as _i6;
import 'package:asklora_mobile_app/feature/onboarding/ppi/domain/ppi_user_response.dart'
    as _i5;
import 'package:asklora_mobile_app/feature/onboarding/ppi/domain/ppi_user_response_request.dart'
    as _i13;
import 'package:asklora_mobile_app/feature/onboarding/ppi/repository/bot_recommendation_repository.dart'
    as _i4;
import 'package:asklora_mobile_app/feature/onboarding/ppi/repository/ppi_response_repository.dart'
    as _i12;
import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBotRecommendationRepository_2 extends _i1.SmartFake
    implements _i4.BotRecommendationRepository {
  _FakeBotRecommendationRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePpiUserResponse_3 extends _i1.SmartFake
    implements _i5.PpiUserResponse {
  _FakePpiUserResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSnapShot_4 extends _i1.SmartFake implements _i5.SnapShot {
  _FakeSnapShot_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignUpRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpRepository extends _i1.Mock implements _i6.SignUpRepository {
  MockSignUpRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.BaseResponse<_i8.SignUpResponse>> signUp({
    required String? email,
    required String? password,
    required String? username,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #username: username,
          },
        ),
        returnValue: _i7.Future<_i2.BaseResponse<_i8.SignUpResponse>>.value(
            _FakeBaseResponse_0<_i8.SignUpResponse>(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #password: password,
              #username: username,
            },
          ),
        )),
      ) as _i7.Future<_i2.BaseResponse<_i8.SignUpResponse>>);
  @override
  _i7.Future<_i2.BaseResponse<_i8.GetOtpResponse>> getVerificationEmail(
          {required _i9.GetOtpRequest? getVerificationEmailRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVerificationEmail,
          [],
          {#getVerificationEmailRequest: getVerificationEmailRequest},
        ),
        returnValue: _i7.Future<_i2.BaseResponse<_i8.GetOtpResponse>>.value(
            _FakeBaseResponse_0<_i8.GetOtpResponse>(
          this,
          Invocation.method(
            #getVerificationEmail,
            [],
            {#getVerificationEmailRequest: getVerificationEmailRequest},
          ),
        )),
      ) as _i7.Future<_i2.BaseResponse<_i8.GetOtpResponse>>);
}

/// A class which mocks [SignUpApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpApiClient extends _i1.Mock implements _i10.SignUpApiClient {
  MockSignUpApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.Response<dynamic>> signUp(_i11.SignUpRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [request],
        ),
        returnValue:
            _i7.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #signUp,
            [request],
          ),
        )),
      ) as _i7.Future<_i3.Response<dynamic>>);
  @override
  _i7.Future<_i3.Response<dynamic>> getActivationEmail(
          _i9.GetOtpRequest? getOtpRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivationEmail,
          [getOtpRequest],
        ),
        returnValue:
            _i7.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getActivationEmail,
            [getOtpRequest],
          ),
        )),
      ) as _i7.Future<_i3.Response<dynamic>>);
}

/// A class which mocks [PpiResponseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPpiResponseRepository extends _i1.Mock
    implements _i12.PpiResponseRepository {
  MockPpiResponseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.BotRecommendationRepository get botRecommendationRepository =>
      (super.noSuchMethod(
        Invocation.getter(#botRecommendationRepository),
        returnValue: _FakeBotRecommendationRepository_2(
          this,
          Invocation.getter(#botRecommendationRepository),
        ),
      ) as _i4.BotRecommendationRepository);
  @override
  _i7.Future<_i5.PpiUserResponse> addAnswer(
          _i13.PpiSelectionRequest? ppiUserResponseRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAnswer,
          [ppiUserResponseRequest],
        ),
        returnValue:
            _i7.Future<_i5.PpiUserResponse>.value(_FakePpiUserResponse_3(
          this,
          Invocation.method(
            #addAnswer,
            [ppiUserResponseRequest],
          ),
        )),
      ) as _i7.Future<_i5.PpiUserResponse>);
  @override
  _i7.Future<_i5.PpiUserResponse> addBulkAnswer(
          List<_i13.PpiSelectionRequest>? ppiUserResponseRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBulkAnswer,
          [ppiUserResponseRequest],
        ),
        returnValue:
            _i7.Future<_i5.PpiUserResponse>.value(_FakePpiUserResponse_3(
          this,
          Invocation.method(
            #addBulkAnswer,
            [ppiUserResponseRequest],
          ),
        )),
      ) as _i7.Future<_i5.PpiUserResponse>);
  @override
  _i7.Future<_i5.SnapShot> getUserSnapShot(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserSnapShot,
          [userId],
        ),
        returnValue: _i7.Future<_i5.SnapShot>.value(_FakeSnapShot_4(
          this,
          Invocation.method(
            #getUserSnapShot,
            [userId],
          ),
        )),
      ) as _i7.Future<_i5.SnapShot>);
  @override
  _i7.Future<_i3.Response<dynamic>> linkUserId(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkUserId,
          [userId],
        ),
        returnValue:
            _i7.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #linkUserId,
            [userId],
          ),
        )),
      ) as _i7.Future<_i3.Response<dynamic>>);
}

/// A class which mocks [SharedPreference].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreference extends _i1.Mock implements _i14.SharedPreference {
  MockSharedPreference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> deleteAllData() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllData,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> deleteData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteData,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<String?> readData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #readData,
          [key],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);
  @override
  _i7.Future<bool> writeData(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
  @override
  _i7.Future<bool> writeIntData(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeIntData,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
  @override
  _i7.Future<int?> readIntData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #readIntData,
          [key],
        ),
        returnValue: _i7.Future<int?>.value(),
      ) as _i7.Future<int?>);
}
