// Mocks generated by Mockito 5.4.0 from annotations
// in asklora_mobile_app/test/tutorial/tutorial_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:asklora_mobile_app/core/repository/tutorial_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TutorialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTutorialRepository extends _i1.Mock
    implements _i2.TutorialRepository {
  MockTutorialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> setBotDetailsTutorial(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setBotDetailsTutorial,
          [value],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> isBotDetailsTutorial() => (super.noSuchMethod(
        Invocation.method(
          #isBotDetailsTutorial,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
