// Mocks generated by Mockito 5.2.0 from annotations
// in asklora_mobile_app/test/sign_out/sign_out_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:asklora_mobile_app/feature/auth/sign_out/domain/sign_out_api_client.dart'
    as _i6;
import 'package:asklora_mobile_app/feature/auth/sign_out/domain/sign_out_request.dart'
    as _i7;
import 'package:asklora_mobile_app/feature/auth/sign_out/domain/sign_out_response.dart'
    as _i2;
import 'package:asklora_mobile_app/feature/auth/sign_out/repository/sign_out_repository.dart'
    as _i4;
import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSignOutResponse_0 extends _i1.Fake implements _i2.SignOutResponse {}

class _FakeResponse_1<T> extends _i1.Fake implements _i3.Response<T> {}

/// A class which mocks [SignOutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutRepository extends _i1.Mock implements _i4.SignOutRepository {
  MockSignOutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SignOutResponse> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
              returnValue:
                  Future<_i2.SignOutResponse>.value(_FakeSignOutResponse_0()))
          as _i5.Future<_i2.SignOutResponse>);
}

/// A class which mocks [SignOutApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutApiClient extends _i1.Mock implements _i6.SignOutApiClient {
  MockSignOutApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Response<dynamic>> signOut(_i7.SignOutRequest? request) =>
      (super.noSuchMethod(Invocation.method(#signOut, [request]),
              returnValue: Future<_i3.Response<dynamic>>.value(
                  _FakeResponse_1<dynamic>()))
          as _i5.Future<_i3.Response<dynamic>>);
}
